[theme]
name = "plain"
[theme.overrides]
idle_bg = "#1c1c1c"
idle_fg = "#6c6c6c"
warning_bg = "#1c1c1c"
warning_fg = "#87875f"
info_bg = "#1c1c1c"
info_fg = "#8fafd7"
good_bg = "#1c1c1c"
good_fg = "#87af87"
critical_bg = "#1c1c1c"
critical_fg = "#ff8700"
separator = ""
separator_bg = "#1c1c1c"
separator_fg = "#444444"

[icons]
name = "none"
[icons.overrides]
time = ""
cogs = ""
cpu = ""

# [[block]]
# block = "bluetooth"
# mac = "2C:41:A1:4A:81:7A"

[[block]]
block = "pacman"
interval = 10

[[block]]
block = "load"
interval = 1
format = "{1m}/{5m}"

[[block]]
block = "cpu"
interval = 1

[[block]]
block = "sound"

[[block]]
block = "time"
interval = 60
format = "%a %d/%m %R"
