[theme]
name = "plain"
[theme.overrides]
idle_bg = "#1c1c1c"
idle_fg = "#6c6c6c"
separator = "  "
separator_bg = "#1c1c1c"
separator_fg = "#444444"

[icons]
name = "none"
[icons.overrides]
time = ""
cogs = ""
cpu = ""

[[block]]
block = "pacman"
interval = 10

[[block]]
block = "load"
interval = 1
format = "{1m}/{5m}"

[[block]]
block = "cpu"
interval = 1

[[block]]
block = "sound"

[[block]]
block = "time"
interval = 60
format = "%a %d/%m %R"
