add_newline = false

[character]      # The name of the module we are configuring is "character"
symbol = ">"     # The "symbol" segment is being set to "➜"

prompt_order=["line_break","package","line_break","character","battery"]

[battery]
full_symbol = "🔋"
charging_symbol = "⚡️"
discharging_symbol = "💀"

[package]
disabled = true

[aws]
disabled = true

[nodejs]
disabled = true

[directory]
style = "fg:15"

[git_branch]
style = "bold"
symbol = ""

[git_status]
style = "fg:3 bold"
